# Generated by Django 5.0.2 on 2024-04-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('rating', models.IntegerField()),
                ('release_date', models.DateField()),
                ('description', models.TextField(null=True)),
                ('created_entry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
